Feature/moneymong 106 회원가입 UI
YAPP-Github/23rd-Android-Team-2-Android pull request #20
Opened 2023-12-12 17:58 UTC by eunseo0105

## 요약
대학교 검색, 학년 선택 UI 개발했습니다.

## 작업내용
<div>
  <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/58fbf4be-bc3d-4567-a796-bc1ac399bfcc" width="200" />
  <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/6890d442-1183-4541-b2e3-193f76cc95a1" width="200" />
  <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/21f96571-3948-4433-a5af-957b4b703098" width="200" />
</div>
<div>
  <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/2637ca27-567c-430c-8702-474f1057547e" width="200" />
  <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/3b478035-7cd0-4e40-b762-38c0a5c8d1fd" width="200" />
  <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/1f4104fe-d4dd-4fc3-9eae-4843ebbd2004" width="200" />
</div>

## 기타
디자인 시스템에 있는  img_congrats 사진 화질이 깨져 img_congrats2로 하나 더 추가했습니다.
수정해야 하는 부분들은 리뷰해주시면 수정해서 다시 커밋 올리겠습니다!

2023-12-13 03:21 UTC, Heonbyeong requested changes
리뷰 반영 부탁드립니다 !

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignCompleteScreen.kt
> +            .padding(MMHorizontalSpacing)
Box가 아닌 레이아웃에서 padding은 가능한 modifier의 속성에서 가장 마지막에 선언해주시길 바랍니다 ! (modifier 속성은 선언된 순서로 반영되기 때문에, 레이아웃이 결과가 완전히 다르게 나올 수 있습니다)

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignCompleteScreen.kt
> +                            .padding(top= 8.dp, bottom= 8.dp),
`.padding(vertical = 8.dp)`도 가능할 것 같아용

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignCompleteScreen.kt
> +        Box(
Box를 한 번 더 감싼 이유가 있을까요 ?

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/AndroidManifest.xml
> +    <application>
해당 내용 삭제 부탁드립니다 ! SAA 구조라서, MainActivity 단일로 가져갈 예정입니다

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +            .padding(MMHorizontalSpacing)
요기도 👀

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +                                    .size(24.dp),
`fillMaxSize()` 속성은 없어도 될 것 같아용

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +    var subTitleState by remember { mutableStateOf(false) }
해당 mutable 값들은 비즈니스 로직 개발 시에, 모두 state로 들어가야 한다는 점 인지하고 계시면 좋을 것 같습니다 !

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +    fun changeSelected(univ:String) {
추후 state로 들어갈 값들이긴 하지만, 지금 당장에 composable 함수 내에서 함수를 선언하지 않고, 람다를 직접 넘기는 방법이 더 좋을 것 같습니다 !
```
SearchUnivView(
        onClick = { isSelected = !isSelected, ... },
        onChange = { textValue = it },
        value = textValue
)
```

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +    fun changeEnabled() {
해당 부분도 위에서 말한 것과 동일합니다

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +                    .padding(0.dp, 8.dp, 0.dp, 0.dp)
값이 0인 부분은 굳이 넣지 않아도 됩니다. `padding(top = 8.dp)` named arg를 활용해주세요 !
(해당 부분도 `SignUpTitleView`의 부모 컴포저블은 `Column`입니다. 의도한 것이 아니라면 `padding`을 제일 마지막에 적용해주세요)

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +            SignUpButtonView(modifier = Modifier.fillMaxWidth(), isEnabled)
파라미터 정렬 및 named arg를 사용해서 가독성을 높여주세요

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/item/UnivItem.kt
> +            .padding(0.dp, 0.dp, 0.dp, 20.dp)
named arg 사용하여 bottom 값만 적용해주시고, 가장 마지막에 padding 속성 적용해주세요 ! (의도한 것이라면 해당 부분은 무시하셔도 됩니다)

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/item/UnivItem.kt
> +fun UnivItem(univs: University, onClick : (String) -> Unit) {
파라미터 줄바꿈

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/item/UnivItem.kt
> +                .padding(10.dp, 0.dp, 0.dp, 0.dp)
named arg 사용하여 start값만 적용해주세요

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SearchUnivView.kt
> +    tvalue = value
tvalue 프로퍼티 선언 시에 value값으로 바로 초기화하면 좋을 것 같아요
`var tvalue by remember { mutableStateOf(value) }`

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SearchUnivView.kt
> +    fun filterUniversities(query: String) {
앞전에 말한 부분과 같은 내용입니다 ! (composeble 함수 내에서 함수 사용)

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SearchUnivView.kt
> +                {
```
isListVisible = if (tvalue.text.isEmpty()) {
   false
}
```
if-else 식 바로 옆에 스코프가 위치할 수 있도록 컨벤션 수정해주세요 !

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SearchUnivView.kt
> +
공백 삭제 부탁드립니다

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignCompleteCheckedView.kt
> +            modifier = Modifier.size(22.dp),
modifier 속성은 composable 파라미터의 맨 처음에 위치하도록 해주세요 (컨벤션)

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignCompleteCheckedView.kt
> +//@Preview
Preview 코드를 주석처리하신 이유가 있을까요 ?

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignCompleteView.kt
> +//        horizontalAlignment = Alignment.CenterHorizontally,
주석 처리한 부분은 삭제 부탁드립니다 !

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignCompleteView.kt
> +            modifier = Modifier
컨벤션

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignCompleteView.kt
> +                modifier = Modifier
컨벤션

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignUpGradeView.kt
> +        Column(
`ctrl + alt + L` (윈도우 단축키가 맞는지 모르겠어요 😅) 눌러서 라인 정렬 부탁드려요 !

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignUpGradeView.kt
> +                modifier = Modifier
컨벤션

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignUpGradeView.kt
> +val GradeList = listOf("1학년", "2학년", "3학년", "4학년", "5학년 이상")
해당 컴포저블 외에 `GradeList`를 쓰는 곳이 있나요 ? 없다면 `SignUpGradeView` 컴포저블 안으로 옮겨주세요 !

2023-12-13 03:21 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignUpTopbarview.kt
> +fun SignUpTopbarview(
코드가 없습니다 👀

2023-12-13 03:30 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignCompleteCheckedView.kt
> +//@Preview
preview로 보다가 screen화면으로 한번에 보는게 편해서 주석했었는데 삭제해놓고 커밋올려놓도록히겠습니다~

2023-12-13 04:36 UTC, jhg3410 requested changes
고생 많으셨습니다👍👍👍 PR Assignees 랑 reviewer 등록해 주시면 감사해요~

2023-12-13 04:36 UTC, jhg3410 commented on core/design-system/src/main/res/drawable/img_congrats2.png
요거 2 로 만들지 마시구 기존 `img_congrats` 를 overwrite 해주시면 매우 감사!!🙂

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignCompleteScreen.kt
> +            .background(White),
`background` 설정이 두 번 들어가 있어요!

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignCompleteScreen.kt
> +}
내부 Box 를 `align` 때문에 사용하신 거라면

```kotlin
Box(
    modifier = modifier
        .fillMaxSize()
        .background(White)
) {
    SignCompleteView(modifier = Modifier.fillMaxSize())
    SignCompleteButtonView(
        modifier = Modifier
            .fillMaxWidth()
            .align(Alignment.BottomCenter)
    )
}
```

이렇게 한 번 해보시겠어요??🙂

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +class SignUpScreenActivity : ComponentActivity() {
저희 기존 MainActivity 말고 따로 Activity 는 만들지 않는 걸로 알고 있어요!

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +            .background(White),
이 친구도 `backgrond` 가 두 번!

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +                            },
![image](https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/80373033/3617c20a-71c6-4d18-b260-1861bdf708b7)

`IconButton` 을 사용하시면 내부적으로 최소 크기를 48 * 48 로 지정하는 걸로 알고 있어요!
그래서 위와 같이 디자인보다 아이콘이 잡아먹는 크기가 더 큰 것으로 보여요!
![image](https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/80373033/da256ed5-1734-40dd-a9bc-cb66a180f820)
위 속성을 무시하시거나 IconButton 말고 다른 방법을 알아보시는 것이 좋아 보여요🧐

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +    )
학년을 선택했을 때 enabled 변경뿐만 아니라 학년에 대한 정보도 받아줘야 하는 것으로 보여요!

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +                    .padding(0.dp, 8.dp, 0.dp, 0.dp)
아규먼트 이름을 사용해서 사용되는 부분만 설정해주시면 감사해요!
```kotlin
// ex)
modifier = Modifier.padding(top = 8.dp)
```

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +                    SearchUnivView(onClick = { selectedUniv -> changeSelected(selectedUniv) }, onChange = {value -> changeValue(value)}, value = textValue)
아규먼트 하나 씩 한 줄로 해주시면 읽을 때 더 좋을 것 같아요!🙂
[코드 자동 정렬](https://blog.jetbrains.com/ko/2020/03/11/top-15-intellij-idea-shortcuts_ko/#⌥⌘l-또는-ctrl+alt+l) 을 자주 사용해 주시면 좋아요!

```kotlin
SearchUnivView(
    onClick = { selectedUniv -> changeSelected(selectedUniv) },
    onChange = { value -> changeValue(value) },
    value = textValue
)
```

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +            SignUpButtonView(modifier = Modifier.fillMaxWidth(), isEnabled)
이것두 요렇게~🧐

```kotlin
SignUpButtonView(
    modifier = Modifier.fillMaxWidth(), 
    isEnabled = isEnabled
)
```

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SearchUnivView.kt
> +fun SearchUnivView(modifier : Modifier = Modifier, onClick : (String) -> Unit, onChange : (TextFieldValue) -> Unit , value : TextFieldValue) {
이것두 파라미터 하나 씩 한 줄로 해주시면 읽기가 편해요!

```kotlin
fun SearchUnivView(
    modifier: Modifier = Modifier,
    onClick: (String) -> Unit,
    onChange: (TextFieldValue) -> Unit,
    value: TextFieldValue
)
```

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SearchUnivView.kt
> +    var tvalue by remember { mutableStateOf(TextFieldValue()) }
파라미터로 들어온 `value` 를 사용 안 하시고  `tvalue` 선언한 이유가 뭘까요??

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SearchUnivView.kt
> +                    )
여기도 코드 정렬 한 번 부탁드려요!🙂

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignCompleteButtonView.kt
> +fun SignCompleteButtonView (modifier: Modifier = Modifier){
`onClick` 파라미터가 필요해 보여요!
- navigation 코드 추가하실 때 넣으셔도 무방해 보여요!

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignCompleteCheckedView.kt
> +fun SignCompleteCheckedView(modifier: Modifier = Modifier , text: String, onChanged : () -> Unit) {
파라미터 하나당 한 줄 씩!🧐

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignCompleteCheckedView.kt
> +                .padding(10.dp, 0.dp, 0.dp, 0.dp)
여기두 사용하는 값만 지정주시면 볼 때 편해요!🧐

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignUpButtonView.kt
> +fun SignUpButtonView(modifier: Modifier = Modifier , isEnabled : Boolean) {
파라미터 하나 당 한 줄씩 해주시면 보기 좋아요~

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignUpGradeView.kt
> +        Column(
맞아요~👍

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignUpGradeView.kt
> +    var selectedIndex  by remember { mutableIntStateOf(-1) }
선택된 학년을 index 보다
`enum class` 로 관리하면 코드가 좀 더 명확해질 것 같아요!

```kotlin
// 예시
enum class Grade(val text: String) {
    FIRST("1학년"),
    SECOND("2학년"),
    THIRD("3학년"),
    FOURTH("4학년"),
    FIFTH_OR_ABOVE("5학년 이상")
}

var selectedGrade: Grade? by remember { mutableIntStateOf(null) }

LazyColumn(items = Grade.values()) { grade ->
    MDSSelection(
        text = Text(grade.text),
        isSelected = grade == selectedGrade,
        onClick = {
            selectedGrade = grade
        }
    )
}
```

2023-12-13 04:36 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignUpTitleView.kt
> +            modifier = Modifier.padding(0.dp, 8.dp, 0.dp, 0.dp),
여기두 코드 정렬이랑 padding 값 지정해 주시면 감사하겠습니다🙂

2023-12-13 08:07 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignUpGradeView.kt
> +    var selectedIndex  by remember { mutableIntStateOf(-1) }
요건 추가로, enum class안에 있는 값은 한글로 설정할 수 있습니다 ! 영단어를 사용하기 애매한 경우라면, 한글을 쓰는 방법도 좋은 방법 중 하나에요 ㅎㅎ

```kotlin
// 예시
enum class Grade() {
    일학년,
    이학년,
    삼학년,
    사학년,
    오학년 이상
}

var selectedGrade: Grade? by remember { mutableIntStateOf(null) }

LazyColumn(items = Grade.values()) { grade ->
    MDSSelection(
        text = Text(grade.text),
        isSelected = grade == selectedGrade,
        onClick = {
            selectedGrade = grade
        }
    )
}
```
물론 요기선 학년 앞에 숫자가 붙어서 일학년, 이학년 이런식으로 썼지만 참고용으로만 봐주세요 😅

2023-12-13 15:00 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignCompleteScreen.kt
> +}
엇 맞아요 align때문에 사용했었는데 한번 수정해볼게요!

2023-12-13 15:01 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignCompleteScreen.kt
> +            .background(White),
이거는 패딩을 주지 않았을 때의 겉화면 색상과 패딩을 준 뒤 안쪽 화면 색상이 달라보여서 백그라운드컬러를 두번 주었던 것인데 아닐까요??

2023-12-13 15:09 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignCompleteScreen.kt
> +        Box(
align 속성을 사용하기 위함이였는데 혹시 더 좋은 방법이 있을까요??

2023-12-14 15:24 UTC, Heonbyeong approved these changes
리뷰 반영사항 확인했습니다~! 고생하셨어요 😌

2023-12-14 15:24 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignCompleteScreen.kt
> +        Box(
`SignCompleteButtonView`의 `modifier` 속성으로 바로 넘겨도 될 것 같아요 !

2023-12-14 16:19 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SearchUnivView.kt
> +                    )
대학교 선택을 한 후 학년 선택 고르기로 전환이 되었는데, 다시 대학교를 수정하고싶을 때 tvalue에서 이전에 textfield에 작성해두었던 내용을 가지고와서 보여줘야하기 때문에 tvalue에 저장해두었던 값을 가져와서 사용했습니다 !

2023-12-14 16:19 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SearchUnivView.kt
> +    var tvalue by remember { mutableStateOf(TextFieldValue()) }
대학교 선택을 한 후 학년 선택 고르기로 전환이 되었는데, 다시 대학교를 수정하고싶을 때 tvalue에서 이전에 textfield에 작성해두었던 내용을 가지고와서 보여줘야하기 때문에 tvalue에 저장해두었던 값을 가져와서 사용했습니다 !

2023-12-14 16:24 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +                            },
혹시 IconButton말고 다른 방법 알고 계신건 어떤게 있을까요?!

2023-12-15 06:16 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +                            },
전 `Icon` 에 `Modifier.clickable` 을 달아요!🙂

2023-12-15 06:22 UTC, jhg3410 approved these changes
고생하셨습니다!!🙂👍

2023-12-15 06:22 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +                .clickable {
Row 보다 아래 `Icon` 에 달면 어떨까요~?

2023-12-15 06:51 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +                            },
음 죄송해요 다시 생각하고 알아보니 `Size` 를 넣어도 잘 적용이 되었을 것 같아요! 디자인과 상이하게 보였던 이유는 슬랙에 올려주셨던 `TopAppBar` 친구 때문 같네요!😅🙇‍♂️

2023-12-19 06:19 UTC, merged