Feature/moneymong 52 소속가입 UI
YAPP-Github/23rd-Android-Team-2-Android pull request #29
Opened 2023-12-20 15:37 UTC by eunseo0105

## 요약
소속가입 UI 개발했습니다. 
## 작업내용
<img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/58765769-c4e3-420a-af67-c32ed17b7c5d" width="200"/> <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/1b208a01-bd40-4a33-b97d-10b71cb2576e" width="200"/> <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/bba3320d-d08c-4746-ae3c-21ed2dea44b9" width="200"/> <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/cf3335df-2b76-4b43-9f8a-95cf4ecefabb" width="200"/>

## 기타
초대코드는 000000으로 가정하고 개발했습니다.

2023-12-21 14:48 UTC, Heonbyeong approved these changes
고생하셨습니다 ☺️

2023-12-21 14:48 UTC, Heonbyeong commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyCompleteScreen.kt
> +                        modifier = Modifier
`modifier` 속성은 가급적 파라미터의 맨 처음에 !!

2023-12-21 14:48 UTC, Heonbyeong commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyCompleteScreen.kt
> +        AgencyCompleteView(modifier)
`AgencyCompleteView`의 `modifier`는 이유가 있어서 파라미터로 전달받은 `modifier`를 사용하신 걸까요 ?

2023-12-21 14:48 UTC, Heonbyeong commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/component/AgencyCodeVIew.kt
> +                    if (value.isEmpty() || compareError) {
해당 조건문을 `visibleCode` 등의 프로퍼티로 빼서 넣어주는게 더 가독성이 높아질 것 같습니다 !

2023-12-21 14:48 UTC, Heonbyeong commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/component/AgencyCodeVIew.kt
> +                    Spacer(modifier = Modifier.width(10.dp))
Row 속성의 `horizontalArrangement = Arrangement.spaceBy(horizontal = 10.dp)` 으로도 가능합니다 !

2023-12-21 14:50 UTC, Heonbyeong requested changes

2023-12-21 14:50 UTC, Heonbyeong commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/component/AgencyCodeVIew.kt
> +                            modifier = Modifier
코드가 가려졌을 때/보여질 때의 border가 다릅니다 ! 확인 부탁드려용

2023-12-21 17:46 UTC, jhg3410 requested changes
고생하셨습니다!!🙂🙃🙂

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyCompleteScreen.kt
> +            TopAppBar(
TopBar 에 X 아이콘이 빠졌어요!😥

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyCompleteScreen.kt
> +            .padding(MMHorizontalSpacing),
이거 horizontal 에만 들어가야 해요!

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyCompleteScreen.kt
> +fun SignCompleteContent (modifier : Modifier = Modifier ){
`ctrl + alt + l` 이 필요해 보입니다!👍

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/component/AgencyCompleteView.kt
> +                .fillMaxWidth()
요 친구 딱히 필요가 없어보여요!🧐

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/component/AgencyCompleteView.kt
> +            .padding(top = 207.dp, bottom = 208.dp),
혹시 중간 배치때문에 하위 Composable 에 fillMaxWidth 와 TextAlign 을 사용하셨다면
```kotlin
Column(
    horizontalAlignment = Alignment.CenterHorizontally
)
```
위 속성을 사용하면 fillMaxWidth 가 필요 없을지도요!?

2023-12-21 17:46 UTC, jhg3410 commented on gradle/libs.versions.toml
> +constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
이 친구들이 사용이 안 되는 걸로 보여요!🧐

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/component/AgencyCompleteButtonView.kt
> +        Spacer(modifier = Modifier.height(8.dp))
위 리뷰(`AgencyCompleteScreen 35 line`)에서 `MMHorizontalSpacing` 을 vertical 에도 사용을 하셔서 `8.dp` 로 하셨는데 이전 리뷰가 반영되면 이것도 `28.dp` 로 수정되어야 해요!

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyJoinScreen.kt
> +            .background(White),
`background` 가 중복으로 들어가요!

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyJoinScreen.kt
> +            .padding(MMHorizontalSpacing)
이건 horizontal 에만!

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyJoinScreen.kt
> +    fun CompareError(): Boolean {
일반 함수인데 첫 글자가 대문자로 시작해요!

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/component/AgencyCodeVIew.kt
> +fun AgencyCodeView(
![image](https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/80373033/66c63f4f-f368-4355-bad7-1c163c97c106)

AgencyCodeView 보다 AgencyInviteCodeView 는 어떨까요??

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/component/AgencyCodeVIew.kt
> +                Row(
Row 가 이중으로 들어간 이유가 있을까요??

2023-12-21 17:46 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/component/AgencyCodeVIew.kt
> +                .height(18.dp),
`Text` 에 `height` 가 고정되어 있으면 디바이스 글자 크기에 따라 짤릴 수도 있어요! ㅠ

2023-12-22 18:28 UTC, eunseo0105 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyCompleteScreen.kt
> +        AgencyCompleteView(modifier)
엇 아니요..ㅎ 수정해놓을게요~

2023-12-22 18:29 UTC, eunseo0105 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyCompleteScreen.kt
> +            TopAppBar(
X 아이콘이 뭘까요...?!

2023-12-23 07:43 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyCompleteScreen.kt
> +            TopAppBar(
![image](https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/80373033/03fb9426-68cf-4bfc-a7ac-b05730c987c0)
!!

2023-12-23 15:26 UTC, eunseo0105 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/component/AgencyCodeVIew.kt
> +                Row(
전체가 column으로 되어있기 때문에 먼저 row로 maxwidth() 가로를 잡고 그 안에 row로 된 textfield들이 하나씩 들어가야해서 이중으로 들어갔습니다!

2023-12-23 15:32 UTC, eunseo0105 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/component/AgencyCodeVIew.kt
> +                    Spacer(modifier = Modifier.width(10.dp))
이렇게 시도했었는데 적용이 안됐었습니다ㅠㅠ

2023-12-24 12:21 UTC, Heonbyeong approved these changes

2023-12-24 20:36 UTC, jhg3410 approved these changes
X 아이콘만 반영해 주시면 매우 감사합니다!! 여행 잘 다녀오십쇼!👍🙇‍♂️

2023-12-25 07:02 UTC, merged