Feature/moneymong 132 멤버 UI
YAPP-Github/23rd-Android-Team-2-Android pull request #30
Opened 2023-12-22 18:27 UTC by eunseo0105

## 요약
멤버 UI 개발했습니다. 
## 작업내용
![KakaoTalk_20231223_032006231](https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/5ddc3803-d254-48cb-982a-adaa17043398) ![KakaoTalk_20231223_032052908](https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/4c15a0f5-002a-4b7d-86ab-341ceba1a737)

## 기타
+ 안드로이드 프로젝트(머니몽)자체가 앱 설치가 안돼서 다른 프로젝트로 코드를 옮겨서 테스트 해봤습니다.
다른 프로젝트에서 코드를 확인해보니 잘 돌아가는데 혹시 몰라서 승인하시기 전에 먼저 제 브랜치로 가셔서 테스트 한번만 부탁드립니다ㅠ ㅠ

2023-12-23 06:37 UTC, Heonbyeong requested changes
리뷰 반영 부탁드립니다

2023-12-23 06:37 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/Member.kt
> +    val type : Int, //예시: 1 - 일반 멤버, 2 - 운영진
멤버의 타입은 Enum class로 관리해주세요 ! (추후 감사 위원회, 가독성 등의 이유)

2023-12-23 06:37 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +    val bottomSheetType = remember { mutableStateOf(1) } //1 = 역할지정/내보내기 , 2= 운영진/ 일반멤버
바텀싯의 타입도 enum으로 관리하는게 좋지 않을까용 ?.?

2023-12-23 06:37 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +    fun onChange() {
위의 상태 프로퍼티 및 함수들은 나중에 모두 state, sideeffect로 빼거나 viewmodel로 이동해야한다는 점 까먹지 마세요 !!

2023-12-23 06:37 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +    if (vertClick.value) {
이런 경우에는
```kotlin
LaunchedEffect(vertClick.value) { ... }
```
을 활용해서 상태 관리를 하는게 어떨까요 ?

2023-12-23 06:37 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +fun Memberscreen() {
as-is -> Memberscreen
to-be -> MemberScreen
수정해주세요 !

2023-12-23 06:37 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +                    .clickable {
제가 core:ui 에 noRippleClickable 이라는 확장함수를 만들어 둔 것이 있습니다. 나중에 그걸로 교체 부탁드려요

2023-12-23 06:37 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/User.kt
> +    val type : Int //예시 : 1 - 일반 멤버, 2 - 운영진
요기도 enum 사용 고려해주세요 ~

2023-12-23 06:37 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +            onIconClick = { onIconClick() }
... 아이콘을 클릭하여 바텀싯을 열었을 때, 이전 바텀싯이 역할 지정으로 설정이 되어있다면 계속해서 역할 지정의 바텀싯이 올라오는 이슈가 있습니다 바텀싯을 닫으면 초기화하는 로직이 필요해 보여요

2023-12-23 06:37 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +                            .weight(1f)
`weight` 속성을 주게되면 역할지정 바텀싯이 화면 전체로 확장되는 이슈가 발생합니다. `weight` 속성을 제거하고, `text`를 기준으로 `padding`을 주는 방법을 고려해보세요 !

2023-12-23 06:37 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +                    MDSButton(
`modifier.fillMaxWitdh().padding() `속성 누락

2023-12-23 09:21 UTC, jhg3410 requested changes
새벽 늦게까지,,, 고생 많으셨습니다!!👍

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +                    .padding(start = 20.dp, end = 20.dp)
`horizontal` 이 있어요!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +        ModalBottomSheet(
Material3 의 ModalBottomSheet  사용하시면

<img width="250" src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/80373033/f1d4e485-c8f9-408b-a748-78cf497723c4">

위 사진처럼 navigationBar 의 영역까지 들어가 버려요!

그래서 전 material  의 ModalBottomSheetLayout 을 사용했었어요
[참고](https://github.com/YAPP-Github/23rd-Android-Team-2-Android/blob/epic/moneymong-124-%EC%86%8C%EC%86%8D/feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/search/AgencySearchScreen.kt)

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +                        painter = painterResource(id = com.moneymong.moneymong.design_system.R.drawable.ic_chevron_right),
`import com.moneymong.moneymong.design_system.R`

처럼 상단에 import 하시면 앞에 `prefix` 를 제거할 수 있어요!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +            .background(White)
`background` 가 두 번!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +            color = Color(0xFF37404F)
`0xFF37404F` => `Gray07` 이에요!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +                    modifier = Modifier.size(29.dp),
디자인 확인했을 때 `44dp` 로 확인됩니다!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +                    painter = painterResource(id = R.drawable.img_profile),
프로필 이미지의 화질이 좋지 않아요 ㅠ  Export 하셔서 `overwrite` 가 필요합니다!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +                    .padding(top = 12.dp, bottom = 12.dp),
`vertical` 있슴다!!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +            .padding(MMHorizontalSpacing)
`horizontal` 만 padding 부탁드립니다!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +                    .height(20.dp)
내부에 `Text` 가 있는데 `height` 를 지정하시면 디바이스 글자 크기에 따라 짤릴 수 있어요!
=> 전 내부 `Composable` 에 `padding` 을 부여하는 방식을 주로 사용합니다!!

<img width = "250" src ="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/80373033/12db0990-8493-4e2d-8fb2-e8f01b4853ea"/>

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberListView.kt
> +        .background(White)
background 가 두 번!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberListView.kt
> +            color = Color(0xFF37404F)
`0xFF37404F` => `Gray07` !

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberListView.kt
> +                itemContent = { MemberListItem(it, onIconClick = { onIconClick() } ) }
`ctrl + alt + l`  해주시면 👍!!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +            modifier = Modifier.padding(top = 24.dp),
`MMHorizontal` 이 vertical 에도 들어가서 최종적으로 44.dp 가 적용되고 있어요!
=> 디자인에선 24.dp 입니다!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +                        .padding(start = 20.dp, end = 20.dp)
`horizontal`!

2023-12-23 09:21 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +                        )
여기도 내부에 Text가  존재해서 height 를 지정하시면 Text가 디바이스 글자 크기에 따라 짤릴 수 있어요!

2023-12-23 16:13 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +        ModalBottomSheet(
엇 이부분은 좀 자세히 확인하고 수정해봐야할 것 같아서 여행같다온 후에 수정해서 커밋 다시 올리도록 하겠습니다ㅠㅠ!

2023-12-23 16:13 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +    if (vertClick.value) {
엇 이부분은 좀 자세히 확인하고 수정해봐야할 것 같아서 여행 갔다온 후에 수정해서 커밋 다시 올리도록 하겠습니다ㅠㅠ!

2023-12-24 12:22 UTC, Heonbyeong approved these changes
🚀

2023-12-25 07:20 UTC, jhg3410 approved these changes
고생하셨습니다!! `BottomSheet` 는 로직 구현하시면서 확인 부탁드려요!~

2023-12-25 07:42 UTC, merged