Feature/moneymong 132 멤버 UI
YAPP-Github/23rd-Android-Team-2-Android pull request #33
Opened 2023-12-26 15:28 UTC by eunseo0105

## 요약
수정된 디자인(복사, 재발급) 으로 변경했습니다. 

## 작업내용

<p align="center">
  <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/d756ec8a-e77b-43f3-a400-da26de036a0b" alt="First Image" width="300"/>
  <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/307fd5c0-af9e-4a4e-97ff-38219b77d285" alt="Second Image" width="300"/>
  <img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/a85b203b-55e2-45ab-944b-99317da5c151" alt="Third Image" width="300"/>
</p>

2023-12-26 15:48 UTC, Heonbyeong approved these changes
고생하셨습니다 ~!

2023-12-26 15:48 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +                    .padding(start = 4.dp, end = 4.dp),
horizontal = 4.dp 도 가능합니다 !

2023-12-26 15:52 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +                    .padding(start = 4.dp, end = 4.dp),
엇 미쳐 확인하지 못했네요 ㅎㅎ 바로 수정했습니다~

2023-12-26 16:46 UTC, jhg3410 approved these changes
확인했습니다~!! 고생하셨어요!👍🙂

2023-12-27 02:57 UTC, Heonbyeong requested changes
epic branch로 pr 올려주세요

2023-12-27 03:04 UTC, Heonbyeong approved these changes

2023-12-27 03:38 UTC, merged