Feature/moneymong 203 로그인/회원가입 기능구현
YAPP-Github/23rd-Android-Team-2-Android pull request #45
Opened 2024-01-15 15:01 UTC by eunseo0105

## 요약
회원가입/로그인 UI 개발했습니다. 
## 작업내용

https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/e936b30b-65cf-4776-ace4-74cf0e14c1ff 

https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/d80dec81-0d2f-42c5-b3f7-56f03883f76a

- 자동로그인 구현
- 카카오 로그인 후 회원가입 진행 

## 기타
MoneyMongAuthenticator 파일에서 리프레쉬 갱신도 만료되었을 경우는 백엔드에서 아직 처리가 안되어 
아직  테스트해보지 못했습니다. 
추후 구현 완료되면 테스트 후 수정사항 반영하도록 하겠습니다.

2024-01-16 07:49 UTC, Heonbyeong requested changes

2024-01-16 07:49 UTC, Heonbyeong commented on app/src/main/res/values/app_secret_key.xml
ignore 처리가 안 된 듯 합니다

2024-01-16 07:49 UTC, Heonbyeong commented on core/network/src/main/java/com/moneymong/moneymong/network/di/NetworkModule.kt
> +    fun provideLoginApi(retrofit: Retrofit): AccessTokenApi {
`api interface`를 피쳐마다 분리한다면 `provider`가 계속해서 생기기 때문에 하나의 인터페이스로 작업하는게 좋을 것 같습니다

2024-01-16 07:49 UTC, Heonbyeong commented on core/network/src/main/java/com/moneymong/moneymong/network/request/login/RefreshTokenRequest.kt
> +    val refreshToken: String
`refreshToken`을 `data class`로 한 번 더 감싼 이유가 있을까요 ?

2024-01-16 07:49 UTC, Heonbyeong commented on core/network/src/main/java/com/moneymong/moneymong/network/request/signup/SearchQueryRequest.kt
> +    val searchQuery : String
요것도 `data class`로 한 번 더 감싼 이유가 있을까요 ?

2024-01-16 07:49 UTC, Heonbyeong commented on core/network/src/main/java/com/moneymong/moneymong/network/response/signup/UniversitiesReponse.kt
> +    val universities: List<University>
요것도 👀

2024-01-16 07:49 UTC, Heonbyeong commented on core/network/src/main/java/com/moneymong/moneymong/network/util/AuthInterceptor.kt
> +        val accessToken = runBlocking {
`runBlocking` 대신 `coroutine`의 `join` 혹은 `await`를 사용하는게 더 안전하다고 생각하는데, 은서님 의견은 어떠신가요 ?

2024-01-16 07:49 UTC, Heonbyeong commented on core/network/src/main/java/com/moneymong/moneymong/network/util/MoneyMongTokenAuthenticator.kt
> +            runBlocking {
요기도 위와 동일한 코멘트입니다 (coroutine join/await)

2024-01-16 07:49 UTC, Heonbyeong commented on data/src/main/java/com/moneymong/moneymong/data/datasource/login/LoginLocalDataSource.kt
Response에 Result<T>로 타입 변경해주세요 !

2024-01-16 07:49 UTC, Heonbyeong commented on data/src/main/java/com/moneymong/moneymong/data/datasource/login/TokenRemoteDataSourceImpl.kt
> +    private val accessTokenApi by lazy { accessTokenApiProvider.get() }
`api interface`를 `Provider`로 매핑하여 지연 초기화를 시킨 이유가 있을까요 ?

2024-01-16 07:49 UTC, Heonbyeong commented on data/src/main/java/com/moneymong/moneymong/data/di/DataSourceModule.kt
> +    @Provides
인터페이스는 `Binds annotation`을 사용하는게 더 적절해보입니다. (@Binds + 추상메소드)

2024-01-16 07:49 UTC, Heonbyeong commented on data/src/main/java/com/moneymong/moneymong/data/di/RepositoryModule.kt
> +interface RepositoryModule {
모듈을 inteface로 작성하신 이유가 있을까요 ? (abstract class, abstract function, binds annotation 필요)

2024-01-16 07:49 UTC, Heonbyeong commented on data/src/main/java/com/moneymong/moneymong/data/repository/login/TokenRepositoryImpl.kt
response type은 Result<T> 로 모두 변경해주세요 !

2024-01-16 07:49 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/viewmodel/SignCompleteViewModel.kt
상태가 isCompleteBtnClicked 밖에 없고, sideEffect가 없다면 composable 내부에서 remember를 사용해서 상태 관리를 할 수도 있을 것 같은데, SignCompleteViewModel을 구현하신 이유가 궁금합니다.

2024-01-16 07:49 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/viewmodel/SignUpViewModel.kt
> +                Log.d("University success", it.toString())
`univUseCase` `api` 호출 성공 시 동작은 따로 없는 걸까요 ?

2024-01-16 07:49 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignCompleteButtonView.kt
> +                viewModel.isCompleteBtnClicked()
단일 람다를 넘기는 경우에는 리플렉션 사용을 고려해주세요 ! (컨벤션)

2024-01-16 07:49 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SearchUnivView.kt
> +                job = scope.launch {
`TextField` 입력 값이 변함에 따라 `api` 호출을 하는 코드로  보입니다. `Throttling` 방식으로 구현하는게 좋을 것 같습니다

2024-01-16 07:49 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/state/SignUpState.kt
> +    val universityResponse: UniversitiesEntity = UniversitiesEntity(
state에서 dto의 초기값은 null로 두는 것이 좋을 것 같습니다. ` val universitryResponse: UniversitiesEntity? = null`

2024-01-16 07:49 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/sideeffect/SignUpSideEffect.kt
> +sealed interface SignUpSideEffect : SideEffect {
`sideEffect`는 `sealed class`로 통일합니다 !

2024-01-16 07:49 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SplashScreen.kt
> +    navController: NavHostController
최상의 컴포저블의 `navigate` 파라미터는, `navController` 보다는 `navController::navigateTo~~ `으로 람다를 받는 것이 좋을 것 같습니다

2024-01-16 07:49 UTC, Heonbyeong commented on domain/src/main/java/com/moneymong/moneymong/domain/repository/TokenRepository.kt
Response에 Result<T> 매핑이 필요합니다 !

2024-01-16 07:49 UTC, Heonbyeong commented on domain/src/main/java/com/moneymong/moneymong/domain/usecase/login/LoginUseCase.kt
> +class LoginUseCase @Inject constructor(
`BaseUseCase`를 사용해주시고, `UseCase`와 비즈니스 로직은 1:1 관계를 최대한 지향합니다

2024-01-16 07:49 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/LoginScreen.kt
> +    navController: NavHostController
`navController::navigateTo~~ `권장

2024-01-16 07:49 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignCompleteScreen.kt
> +    viewModel: SignCompleteViewModel
하위 컴포저블에서, hiltViewModel()로 디폴트 파라미터를 지정하는 뷰가 있고, 부모로부터 받아오는 뷰도 있습니다. 통일이 필요할 것 같습니다.

2024-01-16 07:49 UTC, Heonbyeong commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/item/UnivItem.kt
> +    univs: UniversityX,
`UniversityX`로 이름을 변경하신 이유가 있을까요 ?

2024-01-16 14:28 UTC, jhg3410 requested changes
고생하셨습니다!!

2024-01-16 14:28 UTC, jhg3410 commented on data/src/main/java/com/moneymong/moneymong/data/datasource/login/LoginRemoteDataSourceImpl.kt
> +    ) {
한 줄로 부탁드려요~!!
아래 함수도요!
```kotlin
override suspend fun loginWithKakaoTalk() {
    // ~~
}

2024-01-16 14:28 UTC, jhg3410 commented on core/network/src/main/java/com/moneymong/moneymong/network/response/ErrorResponse.kt
>      val status: Int,
`@SerializedName` 을 추가하신 이유가 어떻게 될까요??

2024-01-16 14:28 UTC, jhg3410 commented on data/src/main/java/com/moneymong/moneymong/data/di/DataSourceModule.kt
> +class DataSourceModule {
`includes = [NetworkModule::class]`
해당 코드는 어떤 역할을 하나요??

2024-01-16 14:28 UTC, jhg3410 commented on core/network/src/main/java/com/moneymong/moneymong/network/response/signup/University.kt
> +)
해당 data class 는  UniversityResponse 파일 내부에 넣는 게 좀 더 깔끔하다고 생각합니다!

2024-01-16 14:28 UTC, jhg3410 commented on domain/src/main/java/com/moneymong/moneymong/domain/entity/signup/UniversityX.kt
> +)
`UniversityX` 라는 네이밍이 무엇을 뜻하는 지 모르겠어요 ㅠ

2024-01-16 14:28 UTC, jhg3410 commented on domain/src/main/java/com/moneymong/moneymong/domain/entity/signup/University.kt
> +)
해당 코드와 UnivEntity 와 무슨 차이가 있는지 모르겠어요!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +                )
줄맞춤 굿!!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/viewmodel/SignUpViewModel.kt
> +    }
TextField 값 변경 시엔 `blockIntent` 를 사용해 주세요!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignUpScreen.kt
> +                }
sideEffect 를 post 하는 부분은 viewModel 에서 따로 함수로 관리하는 게 좋다고 생각해요!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/util/Grade.kt
> +fun gradeNumber(grade : String) : Int{
`getGradeNumber` 이 좋아보입니다!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/item/UnivItem.kt
> +    viewModel: SignUpViewModel = hiltViewModel()
`하위컴포저블(Item)` 에서 ViewModel 을 가지기보단 
`최상위 컴포저블(Screen)` 이 ViewModel 에서 필요한 값(파라미터), 로직를 하위로 내려주는 형태로 가져가야 한다고 생각합니다!

현재 은서님 코드는 대부분의 Item, View 들이 자체적으로 viewModel 을 가지고 있어요!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SearchUnivView.kt
> +                    viewModel.isListVisibleChanged(true)
이전 코드의 주석은 삭제 부탁드립니다!!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignUpGradeView.kt
>  ) {
`gradeInfor` 라는 네이밍 대신 
동사로 시작하는 `changeGradeInfor` 는 어떨까요??

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/viewmodel/SignUpViewModel.kt
> +        reduce {
느낌표 두 개는 위험합니다`!!`

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/SignCompleteCheckedView.kt
> +            }
줄바꿈 부탁드려요!!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/LoginScreen.kt
> +    }
위와 같이 변경한 뒤 다른 화면으로 이동하면 statusbar 가 그대로 Blue04 로 예상됩니다!
`DisposableEffect` 를 사용하면 어떨까요??

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/view/TitleView.kt
> +        horizontalAlignment  = Alignment.CenterHorizontally,
ctrl+alt+L  이 필요합니다!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SplashScreen.kt
>      }
key 값이 true 인 이유가 있을까요? key 값을 활용하지 않으려는 목적이라면 Unit 이 더 좋아 보입니다!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SplashScreen.kt
> +        viewModel.checkTokenValidity()
`delay(1)` 은 왜 있을까요??

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/LoginScreen.kt
> +        }
`if` `else` 로만 가능해보여요!
```kotlin
if (state.isSchoolInfoExist) {
    navController.navigate(homeRoute) {
        popUpTo(loginRoute) { inclusive = true }
    }
} else {
    navController.navigate(signUpRoute) {
        popUpTo(loginRoute) { inclusive = true }
    }
}
```

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SplashScreen.kt
> +
sideEffect 를 post 하는 부분은 viewModel 에서 함수로 구현하는 게 좋아 보여요!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/viewmodel/LoginViewModel.kt
> +                }
```kotlin
override suspend fun onLoginSuccess() {
    reduce {
        state.copy(
            isSchoolInfoExist = loginUseCase.getSchoolInfo()
        )
    }
}
```

이렇게 바꿀 수 있을 것 같아요!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/LoginScreen.kt
> +        if (state.isLoginRequired == true) {
`ctrl + alt + L` 이 필요합니다!

2024-01-16 14:28 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SignCompleteScreen.kt
> +            )
`viewModel` 을 넘겨주기보단 필요한 요소와 로직을 넘겨주세요!

2024-01-21 07:42 UTC, eunseo0105 commented on core/network/src/main/java/com/moneymong/moneymong/network/request/login/RefreshTokenRequest.kt
> +    val refreshToken: String
보내는 값이 한개더라도 data class를 통해 묶어서 보내야 하는 줄 알았는데 그냥 refreshToken만 보내도 되는건가 보군요..!!

2024-01-21 07:58 UTC, eunseo0105 commented on core/network/src/main/java/com/moneymong/moneymong/network/util/AuthInterceptor.kt
> +        val accessToken = runBlocking {
그런데 Interceptor는 OkHttp의 네트워크 요청/응답을 처리하는 동기적인 컴포넌트여서 coroutineScope를 사용하여 비동기적으로 토큰을 가져오는 것은 Interceptor의 동기적인 실행 흐름과 맞지 않을 수 있다는데 어떻게 생각하시나요??

2024-01-21 08:17 UTC, eunseo0105 commented on data/src/main/java/com/moneymong/moneymong/data/di/RepositoryModule.kt
> +interface RepositoryModule {
단순한 의존성 바인딩만 필요한 경우, 인터페이스를 사용하는 것이 더 적합하다고 생각했는데 추상클래스를 사용해야하는 이유가 있을까요??

2024-01-21 08:23 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/viewmodel/SignUpViewModel.kt
> +                Log.d("University success", it.toString())
이 코드는 유저의 대학정보를 조회하는 코드인데 혹시 추후에 사용해야하는 일이 있을까봐 일부 구현해놓았던건데 사용할 일이 없을 것 같네용 코드 삭제해둘게욤

2024-01-21 08:42 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/viewmodel/SignCompleteViewModel.kt
모든 상태들을 state에서 관리하면 좋을 것 같아 통일시켰었는데, 굳이일까요?

2024-01-21 08:44 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/item/UnivItem.kt
> +    univs: UniversityX,
안드로이드에서 자체적으로 kotlin data class file from JSON을 사용하여 자동으로 만들어진 파일 이름이라 그런 것 같은데 가독성이 안좋으면 이름 바꿔두겠습니다!

2024-01-22 14:46 UTC, Heonbyeong commented on core/network/src/main/java/com/moneymong/moneymong/network/request/login/RefreshTokenRequest.kt
> +    val refreshToken: String
`api`에서 `body param`으로 받는다면 `data class`로 매핑을 해야하긴 합니다 !

2024-01-22 14:56 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SplashScreen.kt
> +        viewModel.checkTokenValidity()
spalsh 처음 시작할  때 1초 지연이 존재하더라구요 !!

2024-01-22 14:59 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/LoginScreen.kt
> +        }
저렇게 else로 두면 처음 로그인화면이 그려질 때 바로 state.isSchoolInfoExist가 else에 걸려서 로그인 화면으로 이동하게 도지 않나요 ?

2024-01-22 15:02 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/viewmodel/LoginViewModel.kt
> +                }
Result<Boolean>으로 바껴서 .onSuccess와 .onFailure로 처리해줬습니다!

2024-01-22 15:34 UTC, eunseo0105 commented on data/src/main/java/com/moneymong/moneymong/data/di/DataSourceModule.kt
> +class DataSourceModule {
제가 알기론 DataSourceModule 내부에서 NetworkModule에서 제공하는 의존성들(예: Retrofit 인스턴스, 네트워크 서비스 등)이 필요하다면 저렇게 넣는걸로 알고있긴합니다만...!.. :thinking_face:

2024-01-22 15:35 UTC, eunseo0105 commented on core/network/src/main/java/com/moneymong/moneymong/network/response/ErrorResponse.kt
>      val status: Int,
엇 이걸 왜추가했을까요 당장 삭제 진행하도록 하겠슴다..ㅋㅋㅋㅋ

2024-01-23 04:15 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SplashScreen.kt
> +        viewModel.checkTokenValidity()
1초라면 `delay(1000)` 입니다!

2024-01-23 04:32 UTC, jhg3410 commented on data/src/main/java/com/moneymong/moneymong/data/di/DataSourceModule.kt
> +class DataSourceModule {
이번에 처음 봐서 한 번 찾아봤는데요!

https://dagger.dev/hilt/migration-guide.html

> In general, you shouldn’t need to use @Module(includes=) with Hilt, so if you see that, you’ll want to remove it and just put an @InstallIn annotation on the included module.

dagger -> hilt 마이그레이션 가이드 문서에서 일반적으로 `hilt` 에선 사용할 필요가 없다고 합니다!

어떻게 생각하실까요???

2024-01-23 04:37 UTC, jhg3410 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/LoginScreen.kt
> +        }
아 `isSchoolInfoExist` 친구가 `nullable` 이였군요!😅

2024-01-23 05:29 UTC, eunseo0105 commented on data/src/main/java/com/moneymong/moneymong/data/di/DataSourceModule.kt
> +class DataSourceModule {
그러네요...! 빼도될것같아요ㅎㅎ

2024-01-23 11:54 UTC, eunseo0105 commented on feature/sign/src/main/java/com/moneymong/moneymong/feature/sign/SplashScreen.kt
> +        viewModel.checkTokenValidity()
아 1초가 아니라 1ms입니다..ㅎ

2024-01-24 14:08 UTC, Heonbyeong commented on core/network/src/main/java/com/moneymong/moneymong/network/util/AuthInterceptor.kt
> +        val accessToken = runBlocking {
coroutine job의 join을 사용하면 안전하게 가져올 수 있을 것 같습니다 !

2024-01-28 06:08 UTC, Heonbyeong approved these changes
고생하셨습니다 !

2024-01-28 09:54 UTC, jhg3410 approved these changes
고생하셨습니다!

2024-01-29 12:23 UTC, merged