Feature/moneymong 147 소속가입 기능구현
YAPP-Github/23rd-Android-Team-2-Android pull request #50
Opened 2024-01-21 09:25 UTC by eunseo0105

## 요약
소속 초대코드 기능 구현 완료했습니다. 

## 작업내용

https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/0c7105b9-3c2f-495d-8cf0-ddaccc689bc3

## 기타

2024-01-22 01:08 UTC, Heonbyeong requested changes

2024-01-22 01:08 UTC, Heonbyeong commented on core/network/src/main/java/com/moneymong/moneymong/network/api/agency/AgencyJoinApi.kt
> +    suspend fun agencyCodeNumbers(
해당 `API`도 `MoneyMongApi interface`로 옮겨주세요 !

2024-01-22 01:08 UTC, Heonbyeong commented on core/network/src/main/java/com/moneymong/moneymong/network/di/agency/AgencyJoinApiProvider.kt
사용하지 않는 파일은 삭제 부탁드립니다

2024-01-22 01:08 UTC, Heonbyeong commented on domain/src/main/java/com/moneymong/moneymong/domain/usecase/AgencyJoinUseCase.kt
`BaseUseCase` 사용해주세요 ! (`agencyId`와 `AgencyJoinParam` 두 개를 넘겨야 해서 사용하지 못하셨다면, `AgencyJoinParam` 안에 `agencyId`를 넣어주세요)

2024-01-22 01:08 UTC, Heonbyeong commented on feature/agency/build.gradle.kts
사용하지 않는 코드 및 공백은 삭제 부탁드립니다

2024-01-22 01:08 UTC, Heonbyeong commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyCompleteScreen.kt
> +    navController: NavHostController,
`navController`를 사용하지 않는 것 같습니다. 삭제 부탁드려요 !

2024-01-22 01:08 UTC, Heonbyeong commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyCompleteState.kt
> +    val isBtnClicked : Boolean? = null
`state`에서 원시타입 기본값은 `nullable`를 지양하는 것이 좋다고 생각합니다. `val isBtnClicked : Boolean = false`

2024-01-22 12:42 UTC, jhg3410 requested changes
고생 많으셨어요! 화이팅!!🙂

2024-01-22 12:42 UTC, jhg3410 commented on data/src/main/java/com/moneymong/moneymong/data/datasource/mock/AgencyRemoteDataSourceMock.kt
> +
요 파일은 mock 으로 처리하는 테스트용 파일이에요!
실제 `api` 를 사용하는 코드는 datasource/impl 폴더에 `AgencyRemoteDataSourceImpl` 파일을 새로 만드셔서 넣어주시면 감사하겠습니다🙂
+) 
```kotlin
return agencyJoinApi.agencyCodeNumbers(
        authToken = "BearereyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcklkIjozLCJpYXQiOjE3MDQ3MTU0NTEsImV4cCI6MTczNjI3MzA1MX0.2yYEy71Gz4YIz0DYzlx0glYMgZA0JAZs05jsVRvvQx4",
        agencyId = agencyId,
        AgencyJoinRequest = codeNumbers
    )
```
요런식으로 아규먼트명을 함께 넣어주시면 코드 리뷰할 때, 추후 코드 읽을 때 좋아요!~

2024-01-22 12:42 UTC, jhg3410 commented on feature/agency/build.gradle.kts
의미가 있지 않은 주석은 제거해 주시면 감사하겠습니다!🙂

2024-01-22 12:42 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/AgencyCompleteScreen.kt
>          )
`viewModel` 을 넘겨주지 않고 필요한 로직과 값을 넘겨주시면 감사하겠습니다!

2024-01-22 12:42 UTC, jhg3410 commented on feature/agency/src/main/java/com/moneymong/moneymong/feature/agency/join/navigation/AgencyCompleteNavigation.kt
> +            )
`ctrl+alt+L` 부탁드립니다~!

2024-01-23 15:43 UTC, eunseo0105 commented on data/src/main/java/com/moneymong/moneymong/data/datasource/mock/AgencyRemoteDataSourceMock.kt
> +
엇 mock 파일을 impl로 나중에 리팩토링 할 줄 알고 거기에다가 넣어두었던건데 그럼 새로 파서 진행해둘게요!

2024-01-23 15:47 UTC, eunseo0105 commented on data/src/main/java/com/moneymong/moneymong/data/datasource/mock/AgencyRemoteDataSourceMock.kt
> +
그런데 희직님께서 mock파일에 datasource를 의존성 주입받아서 사용하시는데 저도 datasource 파일을 주입 받으면 희직님 함수들도 오버라이드 해야돼서 일단은 mock파일에 두고 Impl로 나중에 파일 이름을 바꿔주시고 거기서 mock함수 지우고 코드 짜주시는게 어떠신지..?

2024-01-26 02:53 UTC, Heonbyeong requested changes
`agencyCodeNumbers`의 바디 파라미터만 확인해주세요 !

2024-01-26 02:53 UTC, Heonbyeong commented on core/network/src/main/java/com/moneymong/moneymong/network/api/MoneyMongApi.kt
> +        @Body body: String,
```kotlin
{
  "invitationCode": "string"
}
```
이런 식으로 바디파람을 받고 있어서, HashMap 사용 혹은 기존 data class 매핑하는 방식으로 진행하셔야 합니다 !

2024-01-28 06:08 UTC, Heonbyeong approved these changes
고생하셨어요 ~!

2024-01-28 10:12 UTC, jhg3410 commented on data/src/main/java/com/moneymong/moneymong/data/datasource/mock/AgencyRemoteDataSourceMock.kt
> +
어떤 말씀인 지 확인했습니다!! 그렇게 진행해요!~

2024-01-28 10:12 UTC, jhg3410 approved these changes
고생하셨습니다!

2024-01-29 12:45 UTC, merged