Feature/moneymong 176 멤버 내보내기 기능구현
YAPP-Github/23rd-Android-Team-2-Android pull request #61
Opened 2024-01-27 09:58 UTC by eunseo0105

## 요약
멤버 내보내기 기능 구현 완료했습니다. 

## 작업내용

https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/d6a83945-0e57-4849-bbde-556b8c2ad889

## 기타
PR 리뷰해주시면 빠르게 수정commit 올리겠습니다! 🙂

2024-01-27 15:27 UTC, Heonbyeong requested changes

2024-01-27 15:27 UTC, Heonbyeong commented on domain/src/main/java/com/moneymong/moneymong/domain/usecase/member/MemberBlockUseCase.kt
BaseUseCase 사용 부탁드립니다 !

2024-01-28 10:19 UTC, jhg3410 approved these changes
고생하셨습니다!

2024-01-28 10:19 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberViewModel.kt
> +    }
`Get` 또는 가져오다를 뜻하는 동사를 함수명 앞에 붙여주시면 감사하겠습니다!

`blockedMemberList` 해당 함수도요!

2024-01-28 11:53 UTC, Heonbyeong approved these changes

2024-01-29 05:49 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberViewModel.kt
> +    }
다시 보니깐 가져오는 동작이 아니네요! ㅠ
내보내기를 하면서 `filteredMemberList` 를 최신화하는 것으로 보여요!
맞으시다면 get 보단 `updateFilteredMemberListByBlock` 과 같은 느낌의 함수명이 좋아 보입니다!

밑에 `blockedMemberList` 도요!

2024-01-29 06:14 UTC, merged