Feature/moneymong 174 멤버 목록 조회 기능구현
YAPP-Github/23rd-Android-Team-2-Android pull request #63
Opened 2024-01-27 10:01 UTC by eunseo0105

## 요약
멤버 목록 조회 기능 구현 완료했습니다. 

## 작업내용
<img src="https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/8b124cfe-21f1-411d-bc5f-e949b23f5f66" width="300">

## 기타
PR 리뷰해주시면 빠르게 수정commit 올리겠습니다! 🙂

2024-01-27 15:35 UTC, Heonbyeong approved these changes
고생하셨어요 !

2024-01-27 15:35 UTC, Heonbyeong commented on data/src/main/java/com/moneymong/moneymong/data/datasource/member/MemberRemoteDataSourceImpl.kt
> +        return moneyMongApi.MemberList(data)
`data` 보다는 `agencyId`가 가독성이 더 좋을 것 같네용

2024-01-27 15:35 UTC, Heonbyeong commented on domain/src/main/java/com/moneymong/moneymong/domain/usecase/member/GetMyInfoUseCase.kt
요건 희직님쪽 작업이라 mock으로 작업하신 걸까요 ?

2024-01-27 15:35 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +            memberMyInfoChanged = { id, userId, nickname, agencyUserRole ->
`sideeffect`로 해당 `api`를 호출하는 방법도 나쁘지 않을 것 같습니다

2024-01-28 03:57 UTC, eunseo0105 commented on domain/src/main/java/com/moneymong/moneymong/domain/usecase/member/GetMyInfoUseCase.kt
네 맞습니다!

2024-01-28 04:02 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +            memberMyInfoChanged = { id, userId, nickname, agencyUserRole ->
혹시 memberMyInfoChanged말씀하시는 거라면 저 부분은 api 호출하는 부분이 아닙니다..!

2024-01-28 12:31 UTC, jhg3410 requested changes
고생하셨습니다!!

2024-01-28 12:31 UTC, jhg3410 commented on core/network/src/main/java/com/moneymong/moneymong/network/api/MoneyMongApi.kt
> +    suspend fun MemberList(
함수명 `getMemberList` 가 어떨까요??
+) 전 개인적으로 `List`보다 `s` 를 붙이는 걸 좋아하긴 합니다!
`datasource` 와 `repository` 에도요!

2024-01-28 12:31 UTC, jhg3410 commented on data/src/main/java/com/moneymong/moneymong/data/datasource/member/MemberRemoteDataSourceImpl.kt
> +        return moneyMongApi.MemberList(data)
+) 같은 파일에 있는 해당 함수들도요!
![image](https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/80373033/5731ade9-7062-4367-b559-84a79e5111c3)

2024-01-28 12:31 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberState.kt
> +    val filteredMemberList : List<AgencyUserEntity> = emptyList()
`memberMyInfoList` 가 실제론 List(또는 관련된) 자료구조가 아니에요!
`memberMyInfo` 라는 네이밍으로 해도 충분하다고 생각합니다.

또한 `memberMyInfoId` 는 아래 `memberMyInfoList` 변수에서 id 를 사용하면 필요가 없는 변수라 생각해요!

2024-01-28 12:31 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +    }
`MemberCardView` 가 recomposition 이 발생할 때마다 해당 코드가 실행될 것으로 예상돼요!
의도하신 것이 아니라면 LaunchedEffect 로 감싸는 것이 필요합니다!

2024-01-28 12:31 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberListView.kt
> +    updateFilteredMemberList(memberMyInfoId)
`MemberListView` 가 recomposition 이 발생할 때마다 해당 함수가 실행될 것으로 예상돼요!
의도하신 것이 아니라면 LaunchedEffect 로 감싸는 것이 필요합니다!

2024-01-28 12:31 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/item/MemberListItem.kt
`if (agencyUser.userId.toLong() != memberMyInfoId)` 참인 상태에만 View 를 그려요!
그렇다면  
해당 Composable를 호출하는 쪽에서
```kotlin
itemContent = { filteredMemberList ->
  if (filteredMemberList.userId.toLong() != memberMyInfoId) {
      MemberListItem(
          filteredMemberList,
          onIconClick = {
              onIconClick(true)
          }
      )
  }
}
```
위처럼 조건문으로 감싸는 게 어떨까요

`memberMyInfoId` 라는 조건문에만 사용되는 변수를 굳이 안 넘겨도 되는 이점이 있어요!

2024-01-28 12:31 UTC, jhg3410 commented on core/network/src/main/java/com/moneymong/moneymong/network/api/MoneyMongApi.kt
> +    suspend fun MemberList(
+)SideEffect 에도 `MemberList` 라고 되어있어요!

2024-01-28 12:47 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +                        .padding(horizontal = 20.dp)
`horizontal` 뿐만 아니라 `bottom` 에도 padding 이 필요합니다!
참고로 24.dp 에요!
```kotlin
.padding(start = 20.dp, end = 20.dp, bottom = 24.dp)
```

2024-01-28 15:20 UTC, eunseo0105 commented on core/network/src/main/java/com/moneymong/moneymong/network/api/MoneyMongApi.kt
> +    suspend fun MemberList(
의견 반영하겠습니다ㅎㅎ

2024-01-28 15:28 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +    }
memberList가 권한변경이나 내보내기 같은 변경사항이 있게 되면 멤버목록 필터링을 해야하기 때문에 recomposition되어야 할 것 같습니다!

2024-01-28 15:28 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/component/MemberListView.kt
> +    updateFilteredMemberList(memberMyInfoId)
updateFilteredMemberList도 마찬가지로 권한변경이나 내보내기 같은 변경사항이 있게 되면 멤버목록 필터링을 해야하기 때문에 recomposition되어야 할 것 같습니다!

2024-01-28 15:30 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/item/MemberListItem.kt
오 좋은 생각인 것 같습니다! :)

2024-01-28 15:38 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/MemberState.kt
> +    val filteredMemberList : List<AgencyUserEntity> = emptyList()
memberMyInfo로 네이밍 수정 변경했습니다~
댜만 memberMyInfoId는 마이몽 유저 정보를 조회하여 id를 추출한 뒤 저장하는 변수이고, 이 변수와 멤버목록 조회에서 id와 일치하는 리스트의 값들을 memberMyInfo로 상태 저장을 해야하기 때문에 있어야 하는 값이라고 생각해요!

2024-01-29 02:01 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberState.kt
> +    val filteredMemberList : List<AgencyUserEntity> = emptyList()
이해했습니다!👍

2024-01-29 05:43 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +    }
해당 코드는 멤버 목록에서 내 정보를 찾아 변경(적용) 하는 것으로 확인돼요!
그런데 본인 스스로 권한 변경 또는 내보내기를 할 수 없는 것으로 알고 있어요!

그래서 `memberList` 가 서버에서 새로 `get`되지 않는 이상 항상 같은 속성(id, userId, nickname, 권한)으로 memberMyInfoChanged 함수를 호출할 것으로 예상해요!
그렇다면 viewModel 에서 멤버 목록들을 가져올 때만 내 정보를 변경(적용) 하면 되지 않을까요??

2024-01-29 05:44 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberListView.kt
> +    updateFilteredMemberList(memberMyInfoId)
권한 변경, 내보내기 하실 때 `viewModel` 에서 이미 멤버 목록을 필터링하는 것으로 확인돼요!
그래서 없어도 잘 동작할 것으로 예상하는데 어떻게 생각하실까요??

2024-01-29 07:21 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/component/MemberListView.kt
> +    updateFilteredMemberList(memberMyInfoId)
viewModel에서 필터링하게 되는 건 권한 변경, 내보내기 같은 이슈가 생겼을 때 필터링이 되는데 처음 멤버화면을 그릴때는 있어야하는 함수라고 생각합니다! 
그럼 LaunchedEffect로 감싸면 될까요~?

2024-01-29 07:23 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +    }
오호 그럼 이부분도 LaunchedEffect로 감싸면 문제가 해결되는 걸까요??

2024-01-29 09:49 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberListView.kt
> +    updateFilteredMemberList(memberMyInfoId)
감싸도 동작할 것 같아요!(테스트 한 번 부탁드립니다!!)
또한 해당 이유일 때 저라면 `viewModel` 에 init 으로 넣을 것 같긴 합니다!

2024-01-29 10:00 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +    }
위 말은 viewModel 에서 멤버 목록을 가져올 때 해당 함수(내 정보를 적용하는)의 동작을 하면 된다는 의미였어요!
그런데 현재 멤버 목록을 들고 오는 코드와 내 id 를 들고 오는 코드가 비동기로 동작해서 쉽지 않아 보이네요!
이따 허들에서 저랑 같이 코드 보면서 얘기해 봐요!!

2024-01-29 12:46 UTC, jhg3410 approved these changes

2024-01-29 13:01 UTC, merged