Feature/moneymong 178 멤버 초대코드 생성하기 기능구현
YAPP-Github/23rd-Android-Team-2-Android pull request #64
Opened 2024-01-27 10:03 UTC by eunseo0105

## 요약
멤버 초대코드 생성하기 기능 구현 완료했습니다. 

## 작업내용

https://github.com/YAPP-Github/23rd-Android-Team-2-Android/assets/101038047/b6e1e38e-9ae3-4ae7-80d3-adc7cfca490a

## 기타
PR 리뷰해주시면 빠르게 수정commit 올리겠습니다! 🙂

2024-01-27 15:41 UTC, Heonbyeong approved these changes
🚀

2024-01-27 15:41 UTC, Heonbyeong commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
> +                viewModel.onCopyClickChanged(false)
바텀싯이나 스낵바 `visible`을 `sideeffect`로 핸들링 하는 방법이 더 좋을 것 같습니다 !

2024-01-28 06:53 UTC, Heonbyeong approved these changes

2024-01-28 11:18 UTC, jhg3410 requested changes
고생 많으셨습니다!

2024-01-28 11:18 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
>              },
`MDSBottomSheet` 이 존재합니다!!

2024-01-28 11:18 UTC, jhg3410 commented on domain/src/main/java/com/moneymong/moneymong/domain/param/member/AgencyIdParam.kt
> +)
어디에도 사용되지 않는 코드에요!

2024-01-28 11:18 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberState.kt
> +    val isInvitationCode: String = ""
`isInvitationCode` 변수명이 `Boolean` 타입을 가질 것이라고 예상돼요!
초대코드를 의미하는 변수가 맞다면 `invitationCode`  가 어떨까요?

2024-01-28 11:18 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberState.kt
> +    val vertClick: Boolean = false,
`vertClick` 변수가 하는 일이 단순히 bottomSheet 의 show/hide 하는 것으로 확인돼요!
그러면 `visibleBottomSheet` 과 같은 변수명이 좀더 직관적으로 생각됩니다

2024-01-28 11:18 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
>      val bottomSheetType = remember { mutableStateOf(BottomSheetType.ROLE_ASSIGNMENT_EXPORT) }
해당 브랜치 실행해 봤는데요!

**동작 순서**
1. 한(`a`) 멤버의 케밥 버튼을 누른다.
2. 바텀싵에서 역할 지정을 클릭하고 나간다.
3. 다른 멤버(`b`)의 케밥 버튼을 클릭한다.
4. 역할 지정/내보내기 선택 바텀싵이 **아닌** 바로 역할 지정하는 바텀싵이 나타난다.

4번에서 역할 지정/내보내기 선택 바텀싵이 나와야 하는데
해당 변수가 이를 조정하는 것으로 생각되고 변경이 필요해요!

2024-01-28 11:18 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +            if (isUserAuthor == "STAFF") {
`String` 보단 `enum class` 로 관리하면 어떨까요??

2024-01-28 11:18 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/MemberState.kt
> +    val isUserAuthor : String = ""
`isUserAuthor` 해당 변수를 변경하는 코드가 없어서 초대 코드 UI 가 실제론 보이지 않아요

2024-01-28 16:10 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/MemberState.kt
> +    val isUserAuthor : String = ""
앗 이부분이 하위 브랜치 멤버 목록 조회로 가보시면
memberCardView.kt에   
`if (memberMyInfo.agencyUserRole == "STAFF") `
이런식으로 유저 멤버의 역할이 만약 운영진일 경우로 변경되어있습니다..!
초대코드 관련된 로직만 이 브랜치에서 하고 멤버에 관한건 하위 브랜치에서 해서 그런 것 같습니다ㅎㅎ

2024-01-28 16:11 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
>              },
MDSBottomSheet이 존재한다는건 어떤 의미일까용..?

2024-01-28 16:13 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
>      val bottomSheetType = remember { mutableStateOf(BottomSheetType.ROLE_ASSIGNMENT_EXPORT) }
엇 이부분도 하위브랜치인 권한변경, 내보내기 브랜치에서 수정되어 있습니다!! 
해당 브랜치는 초대코드 관련 기능 로직만 수정하여 그런 것 같습니다!

2024-01-28 16:17 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +            if (isUserAuthor == "STAFF") {
코드가 아래와 같이 변경되었습니다! (맨 아래 코멘트 읽어주시고 보시면 편할 것 같습니다ㅎㅎ) 
if (memberMyInfo.agencyUserRole == "STAFF") 
String 값으로 설정해두었던 이유가 맴버의 역할을 서버에서 String값으로 받아와서 memberInfoList에 string값으로 저장해두기 때문에 String으로 비교를 했는데 Enum class로 관리해야할까요??

2024-01-28 16:17 UTC, eunseo0105 commented on feature/member/src/main/java/com/example/member/MemberScreen.kt
>              },
이 부분은 바텀싯을 사용하는 권한변경, 내보내기 브랜치에서 수정해두도록 하겠습니다!

2024-01-29 02:10 UTC, jhg3410 commented on feature/member/src/main/java/com/example/member/component/MemberCardView.kt
> +            if (isUserAuthor == "STAFF") {
개인적으로 서버 쪽에선 String 으로 제공해도 enum 으로 뺄 친구들은 빼는 편인데, 현재 코드에선 단순히 if 문(`==STAFF`) 하나만 존재하고 enum 의 기능을 활용할 부분이 크게 없어 보이네요!
그래도 가도 좋습니다!~

2024-01-29 05:08 UTC, jhg3410 approved these changes

2024-01-29 13:21 UTC, merged